spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subway?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: masterpw
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

